import {env} from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {ZodError} from 'zod';
export const defaultBrand={name:'layane-shop',tagline:'Care for your everyday',color:'#205b44',logo:'',phone:'',currency:'MAD'};
export const starterPage={id:'comfort-bundle',name:'Everyday comfort bundle',slug:'everyday-comfort',price:249,comparePrice:399,status:'draft',template:'editorial',language:'ar',headline:'راحة أكثر، كل يوم',description:'اكتشف باقة layane-shop: دهن سنام الجمل مع واقي الركبة. منتجان في باقة واحدة لروتين العناية اليومي.',image:'/assets/bundle.png',benefits:'دهن سنام الجمل 100 مل\nواقي الركبة قابل للتعديل\nتوصيل إلى جميع أنحاء المغرب',cta:'اطلب الآن',sections:[{title:'دهن سنام الجمل',text:'إضافة بسيطة لروتين العناية اليومي.',image:'/assets/balm.png'},{title:'واقي الركبة',text:'تصميم قابل للتعديل ليلائم روتينك.',image:'/assets/brace.png'}],faq:[{q:'كيف يمكنني الطلب؟',a:'املأ استمارة الطلب وسنتواصل معك لتأكيد التفاصيل.'},{q:'كيف يتم الدفع؟',a:'الدفع نقداً عند استلام الطلب.'}],shipping:0,createdAt:new Date().toISOString()};
export function db(){if(!env.DB)throw new Error('Store storage unavailable. Please try again.');return env.DB;}
export async function brand(){const row=await db().prepare("SELECT value FROM settings WHERE key='brand'").first<{value:string}>();return row?JSON.parse(row.value):defaultBrand;}
export async function admin(){const user=await getChatGPTUser();if(!user)throw new Error('AUTH');const owner=await db().prepare("SELECT value FROM settings WHERE key='owner'").first<{value:string}>();if(!owner){await db().prepare("INSERT OR IGNORE INTO settings(key,value) VALUES('owner',?)").bind(user.userId).run();}const check=await db().prepare("SELECT value FROM settings WHERE key='owner'").first<{value:string}>();if(check?.value!==user.userId)throw new Error('FORBIDDEN');return user;}
export function safeImage(v:string){return v===''||/^\/assets\/[a-zA-Z0-9._/-]+$/.test(v)||/^https:\/\/[^\s]+$/.test(v);}
export function error(e:unknown){console.error(e);if(e instanceof ZodError){const first=e.issues[0];return Response.json({error:`Please check ${first.path.join(' › ') || 'your input'}: ${first.message}`},{status:400});}const msg=e instanceof Error?e.message:'Unexpected error';return Response.json({error:msg==='AUTH'?'Please sign in to manage your store.':msg==='FORBIDDEN'?'Only the store administrator can access this area.':msg.includes('UNIQUE')?'That page URL is already in use. Choose another slug.':'Unable to complete this request. Your changes have not been discarded. Please try again.'},{status:msg==='AUTH'?401:msg==='FORBIDDEN'?403:400});}
export function originCheck(r:Request){const o=r.headers.get('origin');if(o&&o!==new URL(r.url).origin)throw new Error('Invalid origin');}
